// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBli8c7N6SS8PB_DvUcXzlScF7K5MFP4jc',
    appId: '1:529367803524:web:54a1b2dcc9c91a034204d1',
    messagingSenderId: '529367803524',
    projectId: 'doctor-app-29fa4',
    authDomain: 'doctor-app-29fa4.firebaseapp.com',
    storageBucket: 'doctor-app-29fa4.appspot.com',
    measurementId: 'G-FWRRCJMZD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFcap0ZJ3WnM5TpbmYuBvvua6sCeQgnOk',
    appId: '1:529367803524:android:ed2ba04f4e466c854204d1',
    messagingSenderId: '529367803524',
    projectId: 'doctor-app-29fa4',
    storageBucket: 'doctor-app-29fa4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEal6-wz9C8i8jmd4Qy1L3oYoXktB-XCk',
    appId: '1:529367803524:ios:68a86774682b49e24204d1',
    messagingSenderId: '529367803524',
    projectId: 'doctor-app-29fa4',
    storageBucket: 'doctor-app-29fa4.appspot.com',
    iosBundleId: 'com.example.doctorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEal6-wz9C8i8jmd4Qy1L3oYoXktB-XCk',
    appId: '1:529367803524:ios:68a86774682b49e24204d1',
    messagingSenderId: '529367803524',
    projectId: 'doctor-app-29fa4',
    storageBucket: 'doctor-app-29fa4.appspot.com',
    iosBundleId: 'com.example.doctorApp',
  );
}
